# Generated by Django 3.2.12 on 2022-10-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20221004_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='modified_by',
        ),
    ]
