# Generated by Django 3.2.12 on 2022-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20221004_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
